name: CI

on:
 push:
  branches:
   - main
 pull_request:

permissions: {}

jobs:
 ci:
  name: Lint & Test
  runs-on: ubuntu-latest
  env:
   CI: true

  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: Setup npm
     uses: npm/action-setup@v2
     with:
      version: 7
      run_install: false

   - name: Setup Node.js 18.x
     uses: actions/setup-node@v3
     with:
      node-version: 18.x
      cache: npm

   - name: Install dependencies
     run: npm install --frozen-lockfile

   - name: Build
     run: npm build

   - name: Lint
     run: npm lint

   - name: Test
     run: npm coverage
